# Generated by Django 4.2.7 on 2024-10-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=4)),
                ('description', models.TextField(max_length=250)),
                ('colour', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='app.recordtype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='app.recordtype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=20)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='app.recordtype')),
            ],
        ),
        migrations.CreateModel(
            name='CoreRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_roles', to='app.recordtype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='CoreField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=20)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_fields', to='app.recordtype')),
            ],
        ),
    ]
