# Generated by Django 4.2.7 on 2024-10-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtype',
            name='prefix',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
