# Generated by Django 4.2.7 on 2024-10-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_recordtype_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.recordtype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.stage')),
            ],
            options={
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RecordField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('is_core', models.BooleanField(default=False)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.recordtype')),
            ],
        ),
    ]
