# Generated by Django 4.2.7 on 2024-10-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stage_options_alter_stage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='role',
            name='stage',
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='RecordField',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
