# Generated by Django 4.2.7 on 2024-10-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_role_record_type_remove_role_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='stage',
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='corefield',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='corefield',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='corefield',
            unique_together={('record_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('record_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('record_type', 'name')},
        ),
        migrations.DeleteModel(
            name='CoreRole',
        ),
        migrations.DeleteModel(
            name='CustomRole',
        ),
    ]
