# Generated by Django 4.2.7 on 2024-10-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customrole_record_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='corefield',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='corefield',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='corefield',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='colour',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='app.recordtype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='CoreRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_roles', to='app.recordtype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stage')),
            ],
        ),
    ]
