# Generated by Django 4.2.7 on 2024-10-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_stage_options_alter_corefield_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='stage',
        ),
        migrations.DeleteModel(
            name='CoreRole',
        ),
        migrations.DeleteModel(
            name='CustomRole',
        ),
    ]
