# Generated by Django 4.2.7 on 2024-10-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customrole_record_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.recordtype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.stage')),
            ],
            options={
                'ordering': ['stage__order', 'name'],
                'unique_together': {('record_type', 'name')},
            },
        ),
    ]
