# Generated by Django 4.2.7 on 2024-10-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_stage_options_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AddField(
            model_name='role',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stage'),
        ),
    ]
