# Generated by Django 4.2.7 on 2024-10-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_role_options_role_is_core_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.stage'),
        ),
    ]
