# Generated by Django 4.2.7 on 2024-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_role_options_role_order_alter_role_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordtype',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='recordtype',
            name='category',
            field=models.CharField(default='Custom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtype',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
