# Generated by Django 4.2.7 on 2024-10-24 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_recordtype_options_recordtype_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_core',
        ),
        migrations.AddField(
            model_name='customfield',
            name='description',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AddField(
            model_name='customfield',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customfield',
            name='show_in_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='term_set',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Term Set can only contain alphanumeric characters and spaces', regex='^[A-Za-z0-9\\s]*$')]),
        ),
        migrations.AddField(
            model_name='customfield',
            name='visible_on_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='correspondence_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='enable_correspondence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('date', 'Date'), ('datetime', 'Date and Time'), ('time', 'Time'), ('dropdown_single', 'Dropdown Single Select'), ('dropdown_multi', 'Dropdown Multi Select'), ('radio', 'Radio'), ('combobox_single', 'Combobox Single Select'), ('combobox_multi', 'Combobox Multi Select')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('record_type', 'name')},
        ),
    ]
