# Generated by Django 4.2.7 on 2024-10-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customfield_options_alter_recordtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='role',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recordtype'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('record_type', 'stage', 'name')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='allow_multiple',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='order',
        ),
    ]
