# Generated by Django 4.2.7 on 2024-10-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
