# Generated by Django 4.2.7 on 2024-10-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_role_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
