# Generated by Django 4.2.7 on 2024-10-26 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_role_allow_multiple_role_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='corefield',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
