# Generated by Django 4.2.7 on 2024-11-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_customfield_wizard_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('dropdown_single', 'Single Select Dropdown'), ('dropdown_multi', 'Multi Select Dropdown'), ('user_role_single', 'Single User Role'), ('date', 'Date Only'), ('time', 'Time Only'), ('datetime', 'Date and Time'), ('user_role_multi', 'Multi User Role'), ('textarea', 'Text Area'), ('radio', 'Radio')], max_length=20),
        ),
    ]
