# Generated by Django 4.2.7 on 2024-11-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'Text Input'), (2, 'Single Select Dropdown'), (3, 'Multi Select Dropdown'), (4, 'Single User Role'), (5, 'Date Only'), (6, 'Time Only'), (7, 'Date and Time'), (8, 'Multi User Role'), (9, 'Text Area'), (10, 'Radio')]),
        ),
    ]
