# Generated by Django 4.2.7 on 2024-11-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='corefield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corefield',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corefield',
            name='visible_on_create',
            field=models.BooleanField(default=True),
        ),
    ]
