# Generated by Django 4.2.7 on 2024-11-14 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_corefield_is_active_corefield_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corefield',
            name='term_set',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Term Set can only contain alphanumeric characters and spaces', regex='^[A-Za-z0-9\\s]*$')]),
        ),
    ]
