# Generated by Django 4.2.7 on 2024-11-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_corefield_sys_category_customfield_sys_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corefield',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='corefield',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
