# Generated by Django 4.2.7 on 2024-11-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_corefield_options_corefield_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefield',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'text'), (2, 'dropdown_single'), (3, 'dropdown_multi'), (4, 'single_user'), (5, 'date'), (6, 'time'), (7, 'datetime'), (8, 'multi_user'), (9, 'textarea'), (10, 'radio')]),
        ),
    ]
